export CONFIG_CNSS_OUT_OF_TREE=y
export CONFIG_CNSS_GENL=y
export CONFIG_CNSS_UTILS=y
export CONFIG_CNSS_PLAT_IPC_QMI_SVC=y
export CONFIG_ICNSS2=y
export CONFIG_ICNSS2_QMI=y
export CONFIG_CNSS_QMI_SVC=y
export CONFIG_WCNSS_MEM_PRE_ALLOC=y
