#define CONFIG_CNSS_OUT_OF_TREE 1
#define CONFIG_CNSS_GENL 1
#define CONFIG_CNSS_UTILS 1
#define CONFIG_CNSS_PLAT_IPC_QMI_SVC 1
#define CONFIG_ICNSS2 1
#define CONFIG_ICNSS2_QMI 1
#define CONFIG_CNSS_QMI_SVC 1
#define CONFIG_WCNSS_MEM_PRE_ALLOC 1
