# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(WLAN_PLATFORM_ROOT),)
WLAN_PLATFORM_ROOT := $(srctree)/techpack/wlan
endif

ccflags-y += -Wmissing-prototypes

ifeq ($(CONFIG_CNSS_OUT_OF_TREE),y)
ccflags-y += -I$(WLAN_PLATFORM_ROOT)/inc
ccflags-y += -I$(WLAN_PLATFORM_ROOT)/cnss_utils
endif

ifeq ($(CONFIG_CNSS_PREALLOC_DEBUG_LEAK),y)
ccflags-y += -DCONFIG_CNSS_PREALLOC_DEBUG_LEAK
endif

obj-$(CONFIG_WCNSS_MEM_PRE_ALLOC) += cnss_prealloc.o
